export const THIS_IS_A_CONSTANT = 'THIS_IS_A_CONSTANT';
export const THIS_IS_ANOTHER_CONST = 'THIS_IS_ANOTHER_CONST';
//HERE IS A COMMENT

export const YET_ANOTHER_CONSTANT = 'YET_ANOTHER_CONSTANT';
export const HOW_LONG_WILL_THIS_GO_ON = 'HOW_LONG_WILL_THIS_GO_ON';
